language: node_js
node_js:
  - "8"
  - "6"

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - rm /tmp/repo -rf
  - mkdir -p /tmp/repo
  - mv ./{.[!.],}* /tmp/repo/
  - mv /tmp/repo ./
  - git clone https://github.com/kulshekhar/mi-node
  - mv mi-node/medapp ./
  - mv mi-node/data ./
  - rm mi-node -rf
  - yarn global add greenkeeper-lockfile@1
  # - pwd
  # - ls -al
  - cd medapp

before_script:
  - cp ./package.json ../repo
  - cp ./yarn.lock ../repo
  - cd ../repo
  - greenkeeper-lockfile-update
  - cd ../medapp

script:
  # - pwd
  # - ls -al
  # - yarn test
  - yarn test:server

after_script:
  - cd ../repo
  - greenkeeper-lockfile-upload
