language: node_js
node_js:
  - "8"
  - "6"

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - git clone https://github.com/kulshekhar/mi-node
  - cp package.json mi-node/
  - cp yarn.lock mi-node/
  - cd mi-node
  - yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

script:
  - yarn test
  - yarn test:server

after_script:
  - greenkeeper-lockfile-upload
