language: node_js
sudo: required
node_js:
  - "8"
  - "6"
  - "10"

addons:
  chrome: stable

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - git clone https://github.com/kulshekhar/mi-node
  - mv mi-node/medapp ./
  - mv mi-node/data ./
  - rm mi-node -rf
  - yarn global add greenkeeper-lockfile@1
# - sed -i -e 's/TRAVIS_COMMIT_RANGE/TRAVIS_COMMIT_RANGE__/g' ~/.config/yarn/global/node_modules/greenkeeper-lockfile/ci-services/travis.js
  - cd medapp

before_script:
  - which google-chrome
  - sudo chown root:$USER /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - cp ./package.json ../
  - cp ./yarn.lock ../
  - cd ../
# - greenkeeper-lockfile-update
  - cd medapp

script:
  # - ls
  - yarn lint
  - yarn test:ci
  - yarn test:server

after_script:
  - cd ../
# - greenkeeper-lockfile-upload
