language: node_js
node_js:
  - "8"
  - "6"

addons:
  chrome: stable

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
#  - rm /tmp/repo -rf
#  - mkdir -p /tmp/repo
#  - mv ./{.[!.],}* /tmp/repo/
#  - mv /tmp/repo ./
  - git clone https://github.com/kulshekhar/mi-node
  - rm ~/.netrc
  - mv mi-node/medapp ./
  - mv mi-node/data ./
  - rm mi-node -rf
  - yarn global add greenkeeper-lockfile@1
  - cd medapp

before_script:
  - cp ./package.json ../
  - cp ./yarn.lock ../
  - cd ../
  - greenkeeper-lockfile-update
  - cd medapp

script:
  - yarn test:ci
  - yarn test:server

after_script:
  - cd ../
  - greenkeeper-lockfile-upload
