language: node_js
node_js:
  - "8"
  - "6"

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - git clone https://github.com/kulshekhar/mi-node
  - cp package.json mi-node/
  - cp yarn.lock mi-node/
  - yarn global add greenkeeper-lockfile@1
  - pwd

before_script:
  - pwd
  - cp -r node_modules mi-node/
  - greenkeeper-lockfile-update

script:
  - pwd
  - cd mi-node
  # - yarn test
  - yarn test:server
  - cd ..

# after_script:
#   - greenkeeper-lockfile-upload
