language: node_js
node_js:
  - "8"
  # - "6"

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - rm /tmp/repo -rf
  - mkdir -p /tmp/repo
  - mv ./{.,}* /tmp/repo/
  - mv /tmp/repo ./
  - git clone https://github.com/kulshekhar/mi-node
  - rm mi-node/.git -rf
  # - cp package.json mi-node/
  # - cp yarn.lock mi-node/
  # - yarn global add greenkeeper-lockfile@1
  - pwd
  - ls -al
  - cd mi-node

before_script:
  - cp ./package.json ../repo
  - cp ./yarn.lock ../repo
  # - cd ../repo
  # - greenkeeper-lockfile-update
  # - cd ../mi-node

script:
  - pwd
  - ls -al
  # - yarn test
  - yarn test:server

# after_script:
#   - greenkeeper-lockfile-upload
